// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActiveRoom {
    pub identity: __sdk::Identity,
    pub room_id: String,
}

impl __sdk::InModule for ActiveRoom {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActiveRoom`.
///
/// Provides typed access to columns for query building.
pub struct ActiveRoomCols {
    pub identity: __sdk::__query_builder::Col<ActiveRoom, __sdk::Identity>,
    pub room_id: __sdk::__query_builder::Col<ActiveRoom, String>,
}

impl __sdk::__query_builder::HasCols for ActiveRoom {
    type Cols = ActiveRoomCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActiveRoomCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
        }
    }
}

/// Indexed column accessor struct for the table `ActiveRoom`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActiveRoomIxCols {
    pub identity: __sdk::__query_builder::IxCol<ActiveRoom, __sdk::Identity>,
    pub room_id: __sdk::__query_builder::IxCol<ActiveRoom, String>,
}

impl __sdk::__query_builder::HasIxCols for ActiveRoom {
    type IxCols = ActiveRoomIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActiveRoomIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActiveRoom {}
