// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActivityEvent {
    pub event_key: String,
    pub room_id: String,
    pub sequence: u64,
    pub kind: String,
    pub summary: String,
    pub occurred_at: __sdk::Timestamp,
}

impl __sdk::InModule for ActivityEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActivityEvent`.
///
/// Provides typed access to columns for query building.
pub struct ActivityEventCols {
    pub event_key: __sdk::__query_builder::Col<ActivityEvent, String>,
    pub room_id: __sdk::__query_builder::Col<ActivityEvent, String>,
    pub sequence: __sdk::__query_builder::Col<ActivityEvent, u64>,
    pub kind: __sdk::__query_builder::Col<ActivityEvent, String>,
    pub summary: __sdk::__query_builder::Col<ActivityEvent, String>,
    pub occurred_at: __sdk::__query_builder::Col<ActivityEvent, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ActivityEvent {
    type Cols = ActivityEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActivityEventCols {
            event_key: __sdk::__query_builder::Col::new(table_name, "event_key"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            summary: __sdk::__query_builder::Col::new(table_name, "summary"),
            occurred_at: __sdk::__query_builder::Col::new(table_name, "occurred_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ActivityEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActivityEventIxCols {
    pub event_key: __sdk::__query_builder::IxCol<ActivityEvent, String>,
    pub room_id: __sdk::__query_builder::IxCol<ActivityEvent, String>,
}

impl __sdk::__query_builder::HasIxCols for ActivityEvent {
    type IxCols = ActivityEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActivityEventIxCols {
            event_key: __sdk::__query_builder::IxCol::new(table_name, "event_key"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActivityEvent {}
