// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BidArgs {
    pub room_id: String,
    pub tricks: u8,
}

impl From<BidArgs> for super::Reducer {
    fn from(args: BidArgs) -> Self {
        Self::Bid {
            room_id: args.room_id,
            tricks: args.tricks,
        }
    }
}

impl __sdk::InModule for BidArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `bid`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait bid {
    /// Request that the remote module invoke the reducer `bid` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`bid:bid_then`] to run a callback after the reducer completes.
    fn bid(&self, room_id: String, tricks: u8) -> __sdk::Result<()> {
        self.bid_then(room_id, tricks, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `bid` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn bid_then(
        &self,
        room_id: String,
        tricks: u8,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl bid for super::RemoteReducers {
    fn bid_then(
        &self,
        room_id: String,
        tricks: u8,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BidArgs { room_id, tricks }, callback)
    }
}
