// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CardPose {
    pub card_key: String,
    pub room_id: String,
    pub card_id: String,
    pub owner: __sdk::Identity,
    pub owner_seat: u8,
    pub logical_location: String,
    pub x_mm: i32,
    pub y_mm: i32,
    pub z_mm: i32,
    pub rx_mdeg: i32,
    pub ry_mdeg: i32,
    pub rz_mdeg: i32,
    pub sequence: u64,
    pub committed_at: __sdk::Timestamp,
}

impl __sdk::InModule for CardPose {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CardPose`.
///
/// Provides typed access to columns for query building.
pub struct CardPoseCols {
    pub card_key: __sdk::__query_builder::Col<CardPose, String>,
    pub room_id: __sdk::__query_builder::Col<CardPose, String>,
    pub card_id: __sdk::__query_builder::Col<CardPose, String>,
    pub owner: __sdk::__query_builder::Col<CardPose, __sdk::Identity>,
    pub owner_seat: __sdk::__query_builder::Col<CardPose, u8>,
    pub logical_location: __sdk::__query_builder::Col<CardPose, String>,
    pub x_mm: __sdk::__query_builder::Col<CardPose, i32>,
    pub y_mm: __sdk::__query_builder::Col<CardPose, i32>,
    pub z_mm: __sdk::__query_builder::Col<CardPose, i32>,
    pub rx_mdeg: __sdk::__query_builder::Col<CardPose, i32>,
    pub ry_mdeg: __sdk::__query_builder::Col<CardPose, i32>,
    pub rz_mdeg: __sdk::__query_builder::Col<CardPose, i32>,
    pub sequence: __sdk::__query_builder::Col<CardPose, u64>,
    pub committed_at: __sdk::__query_builder::Col<CardPose, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for CardPose {
    type Cols = CardPoseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CardPoseCols {
            card_key: __sdk::__query_builder::Col::new(table_name, "card_key"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            card_id: __sdk::__query_builder::Col::new(table_name, "card_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            owner_seat: __sdk::__query_builder::Col::new(table_name, "owner_seat"),
            logical_location: __sdk::__query_builder::Col::new(table_name, "logical_location"),
            x_mm: __sdk::__query_builder::Col::new(table_name, "x_mm"),
            y_mm: __sdk::__query_builder::Col::new(table_name, "y_mm"),
            z_mm: __sdk::__query_builder::Col::new(table_name, "z_mm"),
            rx_mdeg: __sdk::__query_builder::Col::new(table_name, "rx_mdeg"),
            ry_mdeg: __sdk::__query_builder::Col::new(table_name, "ry_mdeg"),
            rz_mdeg: __sdk::__query_builder::Col::new(table_name, "rz_mdeg"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            committed_at: __sdk::__query_builder::Col::new(table_name, "committed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `CardPose`.
///
/// Provides typed access to indexed columns for query building.
pub struct CardPoseIxCols {
    pub card_key: __sdk::__query_builder::IxCol<CardPose, String>,
    pub room_id: __sdk::__query_builder::IxCol<CardPose, String>,
}

impl __sdk::__query_builder::HasIxCols for CardPose {
    type IxCols = CardPoseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CardPoseIxCols {
            card_key: __sdk::__query_builder::IxCol::new(table_name, "card_key"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CardPose {}
