// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Coin {
    pub coin_key: String,
    pub room_id: String,
    pub owner: __sdk::Identity,
    pub coin_id: String,
    pub denomination_cents: u8,
    pub container: String,
    pub x_mm: i32,
    pub y_mm: i32,
    pub z_mm: i32,
    pub sequence: u64,
    pub committed_at: __sdk::Timestamp,
}

impl __sdk::InModule for Coin {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Coin`.
///
/// Provides typed access to columns for query building.
pub struct CoinCols {
    pub coin_key: __sdk::__query_builder::Col<Coin, String>,
    pub room_id: __sdk::__query_builder::Col<Coin, String>,
    pub owner: __sdk::__query_builder::Col<Coin, __sdk::Identity>,
    pub coin_id: __sdk::__query_builder::Col<Coin, String>,
    pub denomination_cents: __sdk::__query_builder::Col<Coin, u8>,
    pub container: __sdk::__query_builder::Col<Coin, String>,
    pub x_mm: __sdk::__query_builder::Col<Coin, i32>,
    pub y_mm: __sdk::__query_builder::Col<Coin, i32>,
    pub z_mm: __sdk::__query_builder::Col<Coin, i32>,
    pub sequence: __sdk::__query_builder::Col<Coin, u64>,
    pub committed_at: __sdk::__query_builder::Col<Coin, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Coin {
    type Cols = CoinCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CoinCols {
            coin_key: __sdk::__query_builder::Col::new(table_name, "coin_key"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            coin_id: __sdk::__query_builder::Col::new(table_name, "coin_id"),
            denomination_cents: __sdk::__query_builder::Col::new(table_name, "denomination_cents"),
            container: __sdk::__query_builder::Col::new(table_name, "container"),
            x_mm: __sdk::__query_builder::Col::new(table_name, "x_mm"),
            y_mm: __sdk::__query_builder::Col::new(table_name, "y_mm"),
            z_mm: __sdk::__query_builder::Col::new(table_name, "z_mm"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            committed_at: __sdk::__query_builder::Col::new(table_name, "committed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Coin`.
///
/// Provides typed access to indexed columns for query building.
pub struct CoinIxCols {
    pub coin_key: __sdk::__query_builder::IxCol<Coin, String>,
    pub owner: __sdk::__query_builder::IxCol<Coin, __sdk::Identity>,
    pub room_id: __sdk::__query_builder::IxCol<Coin, String>,
}

impl __sdk::__query_builder::HasIxCols for Coin {
    type IxCols = CoinIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CoinIxCols {
            coin_key: __sdk::__query_builder::IxCol::new(table_name, "coin_key"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Coin {}
