// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateRoomArgs {
    pub room_id: String,
    pub join_code: String,
    pub display_name: String,
}

impl From<CreateRoomArgs> for super::Reducer {
    fn from(args: CreateRoomArgs) -> Self {
        Self::CreateRoom {
            room_id: args.room_id,
            join_code: args.join_code,
            display_name: args.display_name,
        }
    }
}

impl __sdk::InModule for CreateRoomArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_room`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_room {
    /// Request that the remote module invoke the reducer `create_room` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_room:create_room_then`] to run a callback after the reducer completes.
    fn create_room(
        &self,
        room_id: String,
        join_code: String,
        display_name: String,
    ) -> __sdk::Result<()> {
        self.create_room_then(room_id, join_code, display_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_room` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_room_then(
        &self,
        room_id: String,
        join_code: String,
        display_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_room for super::RemoteReducers {
    fn create_room_then(
        &self,
        room_id: String,
        join_code: String,
        display_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateRoomArgs {
                room_id,
                join_code,
                display_name,
            },
            callback,
        )
    }
}
