// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DealNextRoundArgs {
    pub room_id: String,
}

impl From<DealNextRoundArgs> for super::Reducer {
    fn from(args: DealNextRoundArgs) -> Self {
        Self::DealNextRound {
            room_id: args.room_id,
        }
    }
}

impl __sdk::InModule for DealNextRoundArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `deal_next_round`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait deal_next_round {
    /// Request that the remote module invoke the reducer `deal_next_round` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`deal_next_round:deal_next_round_then`] to run a callback after the reducer completes.
    fn deal_next_round(&self, room_id: String) -> __sdk::Result<()> {
        self.deal_next_round_then(room_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `deal_next_round` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn deal_next_round_then(
        &self,
        room_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl deal_next_round for super::RemoteReducers {
    fn deal_next_round_then(
        &self,
        room_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DealNextRoundArgs { room_id }, callback)
    }
}
