// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameAction {
    pub action_key: String,
    pub room_id: String,
    pub sequence: u64,
    pub seat: u8,
    pub kind: String,
    pub value: u8,
}

impl __sdk::InModule for GameAction {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GameAction`.
///
/// Provides typed access to columns for query building.
pub struct GameActionCols {
    pub action_key: __sdk::__query_builder::Col<GameAction, String>,
    pub room_id: __sdk::__query_builder::Col<GameAction, String>,
    pub sequence: __sdk::__query_builder::Col<GameAction, u64>,
    pub seat: __sdk::__query_builder::Col<GameAction, u8>,
    pub kind: __sdk::__query_builder::Col<GameAction, String>,
    pub value: __sdk::__query_builder::Col<GameAction, u8>,
}

impl __sdk::__query_builder::HasCols for GameAction {
    type Cols = GameActionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameActionCols {
            action_key: __sdk::__query_builder::Col::new(table_name, "action_key"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            seat: __sdk::__query_builder::Col::new(table_name, "seat"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            value: __sdk::__query_builder::Col::new(table_name, "value"),
        }
    }
}

/// Indexed column accessor struct for the table `GameAction`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameActionIxCols {
    pub action_key: __sdk::__query_builder::IxCol<GameAction, String>,
    pub room_id: __sdk::__query_builder::IxCol<GameAction, String>,
}

impl __sdk::__query_builder::HasIxCols for GameAction {
    type IxCols = GameActionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameActionIxCols {
            action_key: __sdk::__query_builder::IxCol::new(table_name, "action_key"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GameAction {}
