// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LeaveRoomArgs {
    pub room_id: String,
}

impl From<LeaveRoomArgs> for super::Reducer {
    fn from(args: LeaveRoomArgs) -> Self {
        Self::LeaveRoom {
            room_id: args.room_id,
        }
    }
}

impl __sdk::InModule for LeaveRoomArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `leave_room`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait leave_room {
    /// Request that the remote module invoke the reducer `leave_room` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`leave_room:leave_room_then`] to run a callback after the reducer completes.
    fn leave_room(&self, room_id: String) -> __sdk::Result<()> {
        self.leave_room_then(room_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `leave_room` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn leave_room_then(
        &self,
        room_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl leave_room for super::RemoteReducers {
    fn leave_room_then(
        &self,
        room_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(LeaveRoomArgs { room_id }, callback)
    }
}
