// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Member {
    pub member_key: String,
    pub room_id: String,
    pub identity: __sdk::Identity,
    pub display_name: String,
    pub seat: Option<u8>,
    pub connected: bool,
}

impl __sdk::InModule for Member {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Member`.
///
/// Provides typed access to columns for query building.
pub struct MemberCols {
    pub member_key: __sdk::__query_builder::Col<Member, String>,
    pub room_id: __sdk::__query_builder::Col<Member, String>,
    pub identity: __sdk::__query_builder::Col<Member, __sdk::Identity>,
    pub display_name: __sdk::__query_builder::Col<Member, String>,
    pub seat: __sdk::__query_builder::Col<Member, Option<u8>>,
    pub connected: __sdk::__query_builder::Col<Member, bool>,
}

impl __sdk::__query_builder::HasCols for Member {
    type Cols = MemberCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MemberCols {
            member_key: __sdk::__query_builder::Col::new(table_name, "member_key"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            seat: __sdk::__query_builder::Col::new(table_name, "seat"),
            connected: __sdk::__query_builder::Col::new(table_name, "connected"),
        }
    }
}

/// Indexed column accessor struct for the table `Member`.
///
/// Provides typed access to indexed columns for query building.
pub struct MemberIxCols {
    pub identity: __sdk::__query_builder::IxCol<Member, __sdk::Identity>,
    pub member_key: __sdk::__query_builder::IxCol<Member, String>,
    pub room_id: __sdk::__query_builder::IxCol<Member, String>,
}

impl __sdk::__query_builder::HasIxCols for Member {
    type IxCols = MemberIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MemberIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
            member_key: __sdk::__query_builder::IxCol::new(table_name, "member_key"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Member {}
