// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::private_hand_card_type::PrivateHandCard;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_hand`.
///
/// Obtain a handle from the [`MyHandTableAccess::my_hand`] method on [`super::RemoteTables`],
/// like `ctx.db.my_hand()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_hand().on_insert(...)`.
pub struct MyHandTableHandle<'ctx> {
    imp: __sdk::TableHandle<PrivateHandCard>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_hand`.
pub struct MyHandTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyHandTableAccessor {
    type Row = PrivateHandCard;
    type Handle<'db> = MyHandTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_hand()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_hand`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyHandTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyHandTableHandle`], which mediates access to the table `my_hand`.
    fn my_hand(&self) -> MyHandTableHandle<'_>;
}

impl MyHandTableAccess for super::RemoteTables {
    fn my_hand(&self) -> MyHandTableHandle<'_> {
        MyHandTableHandle {
            imp: self.imp.get_table::<PrivateHandCard>("my_hand"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyHandInsertCallbackId(__sdk::CallbackId);
pub struct MyHandDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyHandTableHandle<'ctx> {
    type Row = PrivateHandCard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PrivateHandCard> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyHandTableHandle<'ctx> {
    type Row = PrivateHandCard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PrivateHandCard> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyHandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHandInsertCallbackId {
        MyHandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyHandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyHandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHandDeleteCallbackId {
        MyHandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyHandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyHandTableHandle<'ctx> {
    type InsertCallbackId = MyHandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHandInsertCallbackId {
        MyHandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyHandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyHandTableHandle<'ctx> {
    type DeleteCallbackId = MyHandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyHandDeleteCallbackId {
        MyHandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyHandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyHandUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyHandTableHandle<'ctx> {
    type UpdateCallbackId = MyHandUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyHandUpdateCallbackId {
        MyHandUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyHandUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyHandTableHandle<'ctx> {
    type UpdateCallbackId = MyHandUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyHandUpdateCallbackId {
        MyHandUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyHandUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `card_key` unique index on the table `my_hand`,
/// which allows point queries on the field of the same name
/// via the [`MyHandCardKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_hand().card_key().find(...)`.
pub struct MyHandCardKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PrivateHandCard, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MyHandTableHandle<'ctx> {
    /// Get a handle on the `card_key` unique index on the table `my_hand`.
    pub fn card_key(&self) -> MyHandCardKeyUnique<'ctx> {
        MyHandCardKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("card_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MyHandCardKeyUnique<'ctx> {
    /// Find the subscribed row whose `card_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<PrivateHandCard> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PrivateHandCard>("my_hand");
    _table.add_unique_constraint::<String>("card_key", |row| &row.card_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PrivateHandCard>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PrivateHandCard>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PrivateHandCard`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_handQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PrivateHandCard`.
    fn my_hand(&self) -> __sdk::__query_builder::Table<PrivateHandCard>;
}

impl my_handQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_hand(&self) -> __sdk::__query_builder::Table<PrivateHandCard> {
        __sdk::__query_builder::Table::new("my_hand")
    }
}
