// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::room_secret_type::RoomSecret;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_room_capability`.
///
/// Obtain a handle from the [`MyRoomCapabilityTableAccess::my_room_capability`] method on [`super::RemoteTables`],
/// like `ctx.db.my_room_capability()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_room_capability().on_insert(...)`.
pub struct MyRoomCapabilityTableHandle<'ctx> {
    imp: __sdk::TableHandle<RoomSecret>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_room_capability`.
pub struct MyRoomCapabilityTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyRoomCapabilityTableAccessor {
    type Row = RoomSecret;
    type Handle<'db> = MyRoomCapabilityTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_room_capability()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_room_capability`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyRoomCapabilityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyRoomCapabilityTableHandle`], which mediates access to the table `my_room_capability`.
    fn my_room_capability(&self) -> MyRoomCapabilityTableHandle<'_>;
}

impl MyRoomCapabilityTableAccess for super::RemoteTables {
    fn my_room_capability(&self) -> MyRoomCapabilityTableHandle<'_> {
        MyRoomCapabilityTableHandle {
            imp: self.imp.get_table::<RoomSecret>("my_room_capability"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyRoomCapabilityInsertCallbackId(__sdk::CallbackId);
pub struct MyRoomCapabilityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyRoomCapabilityTableHandle<'ctx> {
    type Row = RoomSecret;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoomSecret> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyRoomCapabilityTableHandle<'ctx> {
    type Row = RoomSecret;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoomSecret> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyRoomCapabilityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRoomCapabilityInsertCallbackId {
        MyRoomCapabilityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyRoomCapabilityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyRoomCapabilityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRoomCapabilityDeleteCallbackId {
        MyRoomCapabilityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyRoomCapabilityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyRoomCapabilityTableHandle<'ctx> {
    type InsertCallbackId = MyRoomCapabilityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRoomCapabilityInsertCallbackId {
        MyRoomCapabilityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyRoomCapabilityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyRoomCapabilityTableHandle<'ctx> {
    type DeleteCallbackId = MyRoomCapabilityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRoomCapabilityDeleteCallbackId {
        MyRoomCapabilityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyRoomCapabilityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyRoomCapabilityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyRoomCapabilityTableHandle<'ctx> {
    type UpdateCallbackId = MyRoomCapabilityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyRoomCapabilityUpdateCallbackId {
        MyRoomCapabilityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyRoomCapabilityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyRoomCapabilityTableHandle<'ctx> {
    type UpdateCallbackId = MyRoomCapabilityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyRoomCapabilityUpdateCallbackId {
        MyRoomCapabilityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyRoomCapabilityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `room_id` unique index on the table `my_room_capability`,
/// which allows point queries on the field of the same name
/// via the [`MyRoomCapabilityRoomIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_room_capability().room_id().find(...)`.
pub struct MyRoomCapabilityRoomIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RoomSecret, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MyRoomCapabilityTableHandle<'ctx> {
    /// Get a handle on the `room_id` unique index on the table `my_room_capability`.
    pub fn room_id(&self) -> MyRoomCapabilityRoomIdUnique<'ctx> {
        MyRoomCapabilityRoomIdUnique {
            imp: self.imp.get_unique_constraint::<String>("room_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MyRoomCapabilityRoomIdUnique<'ctx> {
    /// Find the subscribed row whose `room_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RoomSecret> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RoomSecret>("my_room_capability");
    _table.add_unique_constraint::<String>("room_id", |row| &row.room_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RoomSecret>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RoomSecret>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RoomSecret`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_room_capabilityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RoomSecret`.
    fn my_room_capability(&self) -> __sdk::__query_builder::Table<RoomSecret>;
}

impl my_room_capabilityQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_room_capability(&self) -> __sdk::__query_builder::Table<RoomSecret> {
        __sdk::__query_builder::Table::new("my_room_capability")
    }
}
