// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::room_type::Room;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_rooms`.
///
/// Obtain a handle from the [`MyRoomsTableAccess::my_rooms`] method on [`super::RemoteTables`],
/// like `ctx.db.my_rooms()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_rooms().on_insert(...)`.
pub struct MyRoomsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Room>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_rooms`.
pub struct MyRoomsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyRoomsTableAccessor {
    type Row = Room;
    type Handle<'db> = MyRoomsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_rooms()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_rooms`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyRoomsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyRoomsTableHandle`], which mediates access to the table `my_rooms`.
    fn my_rooms(&self) -> MyRoomsTableHandle<'_>;
}

impl MyRoomsTableAccess for super::RemoteTables {
    fn my_rooms(&self) -> MyRoomsTableHandle<'_> {
        MyRoomsTableHandle {
            imp: self.imp.get_table::<Room>("my_rooms"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyRoomsInsertCallbackId(__sdk::CallbackId);
pub struct MyRoomsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyRoomsTableHandle<'ctx> {
    type Row = Room;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Room> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyRoomsTableHandle<'ctx> {
    type Row = Room;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Room> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyRoomsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRoomsInsertCallbackId {
        MyRoomsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyRoomsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyRoomsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRoomsDeleteCallbackId {
        MyRoomsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyRoomsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyRoomsTableHandle<'ctx> {
    type InsertCallbackId = MyRoomsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRoomsInsertCallbackId {
        MyRoomsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyRoomsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyRoomsTableHandle<'ctx> {
    type DeleteCallbackId = MyRoomsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRoomsDeleteCallbackId {
        MyRoomsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyRoomsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MyRoomsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MyRoomsTableHandle<'ctx> {
    type UpdateCallbackId = MyRoomsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyRoomsUpdateCallbackId {
        MyRoomsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyRoomsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MyRoomsTableHandle<'ctx> {
    type UpdateCallbackId = MyRoomsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MyRoomsUpdateCallbackId {
        MyRoomsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MyRoomsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `room_id` unique index on the table `my_rooms`,
/// which allows point queries on the field of the same name
/// via the [`MyRoomsRoomIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_rooms().room_id().find(...)`.
pub struct MyRoomsRoomIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Room, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MyRoomsTableHandle<'ctx> {
    /// Get a handle on the `room_id` unique index on the table `my_rooms`.
    pub fn room_id(&self) -> MyRoomsRoomIdUnique<'ctx> {
        MyRoomsRoomIdUnique {
            imp: self.imp.get_unique_constraint::<String>("room_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MyRoomsRoomIdUnique<'ctx> {
    /// Find the subscribed row whose `room_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Room> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Room>("my_rooms");
    _table.add_unique_constraint::<String>("room_id", |row| &row.room_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Room>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Room>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Room`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_roomsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Room`.
    fn my_rooms(&self) -> __sdk::__query_builder::Table<Room>;
}

impl my_roomsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_rooms(&self) -> __sdk::__query_builder::Table<Room> {
        __sdk::__query_builder::Table::new("my_rooms")
    }
}
