// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayCardArgs {
    pub room_id: String,
    pub card_id: String,
}

impl From<PlayCardArgs> for super::Reducer {
    fn from(args: PlayCardArgs) -> Self {
        Self::PlayCard {
            room_id: args.room_id,
            card_id: args.card_id,
        }
    }
}

impl __sdk::InModule for PlayCardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `play_card`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait play_card {
    /// Request that the remote module invoke the reducer `play_card` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`play_card:play_card_then`] to run a callback after the reducer completes.
    fn play_card(&self, room_id: String, card_id: String) -> __sdk::Result<()> {
        self.play_card_then(room_id, card_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `play_card` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn play_card_then(
        &self,
        room_id: String,
        card_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl play_card for super::RemoteReducers {
    fn play_card_then(
        &self,
        room_id: String,
        card_id: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PlayCardArgs { room_id, card_id }, callback)
    }
}
