// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PrivateHandCard {
    pub card_key: String,
    pub room_id: String,
    pub owner: __sdk::Identity,
    pub card_id: String,
    pub face: String,
}

impl __sdk::InModule for PrivateHandCard {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PrivateHandCard`.
///
/// Provides typed access to columns for query building.
pub struct PrivateHandCardCols {
    pub card_key: __sdk::__query_builder::Col<PrivateHandCard, String>,
    pub room_id: __sdk::__query_builder::Col<PrivateHandCard, String>,
    pub owner: __sdk::__query_builder::Col<PrivateHandCard, __sdk::Identity>,
    pub card_id: __sdk::__query_builder::Col<PrivateHandCard, String>,
    pub face: __sdk::__query_builder::Col<PrivateHandCard, String>,
}

impl __sdk::__query_builder::HasCols for PrivateHandCard {
    type Cols = PrivateHandCardCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PrivateHandCardCols {
            card_key: __sdk::__query_builder::Col::new(table_name, "card_key"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            card_id: __sdk::__query_builder::Col::new(table_name, "card_id"),
            face: __sdk::__query_builder::Col::new(table_name, "face"),
        }
    }
}

/// Indexed column accessor struct for the table `PrivateHandCard`.
///
/// Provides typed access to indexed columns for query building.
pub struct PrivateHandCardIxCols {
    pub card_key: __sdk::__query_builder::IxCol<PrivateHandCard, String>,
    pub owner: __sdk::__query_builder::IxCol<PrivateHandCard, __sdk::Identity>,
    pub room_id: __sdk::__query_builder::IxCol<PrivateHandCard, String>,
}

impl __sdk::__query_builder::HasIxCols for PrivateHandCard {
    type IxCols = PrivateHandCardIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PrivateHandCardIxCols {
            card_key: __sdk::__query_builder::IxCol::new(table_name, "card_key"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PrivateHandCard {}
