// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PrivateCardIdentity {
    pub card_key: String,
    pub room_id: String,
    pub owner: __sdk::Identity,
    pub card_id: String,
    pub face_code: u8,
}

impl __sdk::InModule for PrivateCardIdentity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PrivateCardIdentity`.
///
/// Provides typed access to columns for query building.
pub struct PrivateCardIdentityCols {
    pub card_key: __sdk::__query_builder::Col<PrivateCardIdentity, String>,
    pub room_id: __sdk::__query_builder::Col<PrivateCardIdentity, String>,
    pub owner: __sdk::__query_builder::Col<PrivateCardIdentity, __sdk::Identity>,
    pub card_id: __sdk::__query_builder::Col<PrivateCardIdentity, String>,
    pub face_code: __sdk::__query_builder::Col<PrivateCardIdentity, u8>,
}

impl __sdk::__query_builder::HasCols for PrivateCardIdentity {
    type Cols = PrivateCardIdentityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PrivateCardIdentityCols {
            card_key: __sdk::__query_builder::Col::new(table_name, "card_key"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            card_id: __sdk::__query_builder::Col::new(table_name, "card_id"),
            face_code: __sdk::__query_builder::Col::new(table_name, "face_code"),
        }
    }
}

/// Indexed column accessor struct for the table `PrivateCardIdentity`.
///
/// Provides typed access to indexed columns for query building.
pub struct PrivateCardIdentityIxCols {
    pub card_key: __sdk::__query_builder::IxCol<PrivateCardIdentity, String>,
    pub owner: __sdk::__query_builder::IxCol<PrivateCardIdentity, __sdk::Identity>,
    pub room_id: __sdk::__query_builder::IxCol<PrivateCardIdentity, String>,
}

impl __sdk::__query_builder::HasIxCols for PrivateCardIdentity {
    type IxCols = PrivateCardIdentityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PrivateCardIdentityIxCols {
            card_key: __sdk::__query_builder::IxCol::new(table_name, "card_key"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PrivateCardIdentity {}
