// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RevealedCard {
    pub card_key: String,
    pub room_id: String,
    pub face: String,
}

impl __sdk::InModule for RevealedCard {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RevealedCard`.
///
/// Provides typed access to columns for query building.
pub struct RevealedCardCols {
    pub card_key: __sdk::__query_builder::Col<RevealedCard, String>,
    pub room_id: __sdk::__query_builder::Col<RevealedCard, String>,
    pub face: __sdk::__query_builder::Col<RevealedCard, String>,
}

impl __sdk::__query_builder::HasCols for RevealedCard {
    type Cols = RevealedCardCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RevealedCardCols {
            card_key: __sdk::__query_builder::Col::new(table_name, "card_key"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            face: __sdk::__query_builder::Col::new(table_name, "face"),
        }
    }
}

/// Indexed column accessor struct for the table `RevealedCard`.
///
/// Provides typed access to indexed columns for query building.
pub struct RevealedCardIxCols {
    pub card_key: __sdk::__query_builder::IxCol<RevealedCard, String>,
    pub room_id: __sdk::__query_builder::IxCol<RevealedCard, String>,
}

impl __sdk::__query_builder::HasIxCols for RevealedCard {
    type IxCols = RevealedCardIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RevealedCardIxCols {
            card_key: __sdk::__query_builder::IxCol::new(table_name, "card_key"),
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RevealedCard {}
