// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Room {
    pub room_id: String,
    pub coordinator: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for Room {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Room`.
///
/// Provides typed access to columns for query building.
pub struct RoomCols {
    pub room_id: __sdk::__query_builder::Col<Room, String>,
    pub coordinator: __sdk::__query_builder::Col<Room, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<Room, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Room {
    type Cols = RoomCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RoomCols {
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            coordinator: __sdk::__query_builder::Col::new(table_name, "coordinator"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Room`.
///
/// Provides typed access to indexed columns for query building.
pub struct RoomIxCols {
    pub room_id: __sdk::__query_builder::IxCol<Room, String>,
}

impl __sdk::__query_builder::HasIxCols for Room {
    type IxCols = RoomIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RoomIxCols {
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Room {}
