// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RoomGame {
    pub room_id: String,
    pub seed: u64,
    pub action_count: u64,
    pub phase: String,
    pub actor_seat: Option<u8>,
    pub dealer_seat: Option<u8>,
    pub round_index: u16,
    pub hand_size: u8,
    pub hand_count_0: u8,
    pub hand_count_1: u8,
    pub bid_0: Option<u8>,
    pub bid_1: Option<u8>,
    pub trick_count: u8,
    pub trick_seat_0: Option<u8>,
    pub trick_card_0: Option<u8>,
    pub trick_seat_1: Option<u8>,
    pub trick_card_1: Option<u8>,
    pub tricks_won_0: u8,
    pub tricks_won_1: u8,
    pub score_0: u16,
    pub score_1: u16,
    pub pot_cents: u32,
    pub trump: Option<u8>,
}

impl __sdk::InModule for RoomGame {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RoomGame`.
///
/// Provides typed access to columns for query building.
pub struct RoomGameCols {
    pub room_id: __sdk::__query_builder::Col<RoomGame, String>,
    pub seed: __sdk::__query_builder::Col<RoomGame, u64>,
    pub action_count: __sdk::__query_builder::Col<RoomGame, u64>,
    pub phase: __sdk::__query_builder::Col<RoomGame, String>,
    pub actor_seat: __sdk::__query_builder::Col<RoomGame, Option<u8>>,
    pub dealer_seat: __sdk::__query_builder::Col<RoomGame, Option<u8>>,
    pub round_index: __sdk::__query_builder::Col<RoomGame, u16>,
    pub hand_size: __sdk::__query_builder::Col<RoomGame, u8>,
    pub hand_count_0: __sdk::__query_builder::Col<RoomGame, u8>,
    pub hand_count_1: __sdk::__query_builder::Col<RoomGame, u8>,
    pub bid_0: __sdk::__query_builder::Col<RoomGame, Option<u8>>,
    pub bid_1: __sdk::__query_builder::Col<RoomGame, Option<u8>>,
    pub trick_count: __sdk::__query_builder::Col<RoomGame, u8>,
    pub trick_seat_0: __sdk::__query_builder::Col<RoomGame, Option<u8>>,
    pub trick_card_0: __sdk::__query_builder::Col<RoomGame, Option<u8>>,
    pub trick_seat_1: __sdk::__query_builder::Col<RoomGame, Option<u8>>,
    pub trick_card_1: __sdk::__query_builder::Col<RoomGame, Option<u8>>,
    pub tricks_won_0: __sdk::__query_builder::Col<RoomGame, u8>,
    pub tricks_won_1: __sdk::__query_builder::Col<RoomGame, u8>,
    pub score_0: __sdk::__query_builder::Col<RoomGame, u16>,
    pub score_1: __sdk::__query_builder::Col<RoomGame, u16>,
    pub pot_cents: __sdk::__query_builder::Col<RoomGame, u32>,
    pub trump: __sdk::__query_builder::Col<RoomGame, Option<u8>>,
}

impl __sdk::__query_builder::HasCols for RoomGame {
    type Cols = RoomGameCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RoomGameCols {
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            seed: __sdk::__query_builder::Col::new(table_name, "seed"),
            action_count: __sdk::__query_builder::Col::new(table_name, "action_count"),
            phase: __sdk::__query_builder::Col::new(table_name, "phase"),
            actor_seat: __sdk::__query_builder::Col::new(table_name, "actor_seat"),
            dealer_seat: __sdk::__query_builder::Col::new(table_name, "dealer_seat"),
            round_index: __sdk::__query_builder::Col::new(table_name, "round_index"),
            hand_size: __sdk::__query_builder::Col::new(table_name, "hand_size"),
            hand_count_0: __sdk::__query_builder::Col::new(table_name, "hand_count_0"),
            hand_count_1: __sdk::__query_builder::Col::new(table_name, "hand_count_1"),
            bid_0: __sdk::__query_builder::Col::new(table_name, "bid_0"),
            bid_1: __sdk::__query_builder::Col::new(table_name, "bid_1"),
            trick_count: __sdk::__query_builder::Col::new(table_name, "trick_count"),
            trick_seat_0: __sdk::__query_builder::Col::new(table_name, "trick_seat_0"),
            trick_card_0: __sdk::__query_builder::Col::new(table_name, "trick_card_0"),
            trick_seat_1: __sdk::__query_builder::Col::new(table_name, "trick_seat_1"),
            trick_card_1: __sdk::__query_builder::Col::new(table_name, "trick_card_1"),
            tricks_won_0: __sdk::__query_builder::Col::new(table_name, "tricks_won_0"),
            tricks_won_1: __sdk::__query_builder::Col::new(table_name, "tricks_won_1"),
            score_0: __sdk::__query_builder::Col::new(table_name, "score_0"),
            score_1: __sdk::__query_builder::Col::new(table_name, "score_1"),
            pot_cents: __sdk::__query_builder::Col::new(table_name, "pot_cents"),
            trump: __sdk::__query_builder::Col::new(table_name, "trump"),
        }
    }
}

/// Indexed column accessor struct for the table `RoomGame`.
///
/// Provides typed access to indexed columns for query building.
pub struct RoomGameIxCols {
    pub room_id: __sdk::__query_builder::IxCol<RoomGame, String>,
}

impl __sdk::__query_builder::HasIxCols for RoomGame {
    type IxCols = RoomGameIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RoomGameIxCols {
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RoomGame {}
