// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RoundRecord {
    pub round_key: String,
    pub room_id: String,
    pub round_index: u16,
    pub dealer_seat: u8,
    pub hand_size: u8,
    pub bids: Vec<u8>,
    pub tricks_won: Vec<u8>,
    pub points: Vec<u16>,
    pub totals: Vec<u16>,
    pub payment_cents: Vec<u32>,
}

impl __sdk::InModule for RoundRecord {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RoundRecord`.
///
/// Provides typed access to columns for query building.
pub struct RoundRecordCols {
    pub round_key: __sdk::__query_builder::Col<RoundRecord, String>,
    pub room_id: __sdk::__query_builder::Col<RoundRecord, String>,
    pub round_index: __sdk::__query_builder::Col<RoundRecord, u16>,
    pub dealer_seat: __sdk::__query_builder::Col<RoundRecord, u8>,
    pub hand_size: __sdk::__query_builder::Col<RoundRecord, u8>,
    pub bids: __sdk::__query_builder::Col<RoundRecord, Vec<u8>>,
    pub tricks_won: __sdk::__query_builder::Col<RoundRecord, Vec<u8>>,
    pub points: __sdk::__query_builder::Col<RoundRecord, Vec<u16>>,
    pub totals: __sdk::__query_builder::Col<RoundRecord, Vec<u16>>,
    pub payment_cents: __sdk::__query_builder::Col<RoundRecord, Vec<u32>>,
}

impl __sdk::__query_builder::HasCols for RoundRecord {
    type Cols = RoundRecordCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RoundRecordCols {
            round_key: __sdk::__query_builder::Col::new(table_name, "round_key"),
            room_id: __sdk::__query_builder::Col::new(table_name, "room_id"),
            round_index: __sdk::__query_builder::Col::new(table_name, "round_index"),
            dealer_seat: __sdk::__query_builder::Col::new(table_name, "dealer_seat"),
            hand_size: __sdk::__query_builder::Col::new(table_name, "hand_size"),
            bids: __sdk::__query_builder::Col::new(table_name, "bids"),
            tricks_won: __sdk::__query_builder::Col::new(table_name, "tricks_won"),
            points: __sdk::__query_builder::Col::new(table_name, "points"),
            totals: __sdk::__query_builder::Col::new(table_name, "totals"),
            payment_cents: __sdk::__query_builder::Col::new(table_name, "payment_cents"),
        }
    }
}

/// Indexed column accessor struct for the table `RoundRecord`.
///
/// Provides typed access to indexed columns for query building.
pub struct RoundRecordIxCols {
    pub room_id: __sdk::__query_builder::IxCol<RoundRecord, String>,
    pub round_key: __sdk::__query_builder::IxCol<RoundRecord, String>,
}

impl __sdk::__query_builder::HasIxCols for RoundRecord {
    type IxCols = RoundRecordIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RoundRecordIxCols {
            room_id: __sdk::__query_builder::IxCol::new(table_name, "room_id"),
            round_key: __sdk::__query_builder::IxCol::new(table_name, "round_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RoundRecord {}
