// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TakeSeatArgs {
    pub room_id: String,
    pub seat: u8,
}

impl From<TakeSeatArgs> for super::Reducer {
    fn from(args: TakeSeatArgs) -> Self {
        Self::TakeSeat {
            room_id: args.room_id,
            seat: args.seat,
        }
    }
}

impl __sdk::InModule for TakeSeatArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `take_seat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait take_seat {
    /// Request that the remote module invoke the reducer `take_seat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`take_seat:take_seat_then`] to run a callback after the reducer completes.
    fn take_seat(&self, room_id: String, seat: u8) -> __sdk::Result<()> {
        self.take_seat_then(room_id, seat, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `take_seat` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn take_seat_then(
        &self,
        room_id: String,
        seat: u8,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl take_seat for super::RemoteReducers {
    fn take_seat_then(
        &self,
        room_id: String,
        seat: u8,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(TakeSeatArgs { room_id, seat }, callback)
    }
}
