// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::coin_type::Coin;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_coins`.
///
/// Obtain a handle from the [`VisibleCoinsTableAccess::visible_coins`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_coins()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_coins().on_insert(...)`.
pub struct VisibleCoinsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Coin>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_coins`.
pub struct VisibleCoinsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleCoinsTableAccessor {
    type Row = Coin;
    type Handle<'db> = VisibleCoinsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_coins()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_coins`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleCoinsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleCoinsTableHandle`], which mediates access to the table `visible_coins`.
    fn visible_coins(&self) -> VisibleCoinsTableHandle<'_>;
}

impl VisibleCoinsTableAccess for super::RemoteTables {
    fn visible_coins(&self) -> VisibleCoinsTableHandle<'_> {
        VisibleCoinsTableHandle {
            imp: self.imp.get_table::<Coin>("visible_coins"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleCoinsInsertCallbackId(__sdk::CallbackId);
pub struct VisibleCoinsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleCoinsTableHandle<'ctx> {
    type Row = Coin;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Coin> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleCoinsTableHandle<'ctx> {
    type Row = Coin;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Coin> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleCoinsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleCoinsInsertCallbackId {
        VisibleCoinsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleCoinsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleCoinsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleCoinsDeleteCallbackId {
        VisibleCoinsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleCoinsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleCoinsTableHandle<'ctx> {
    type InsertCallbackId = VisibleCoinsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleCoinsInsertCallbackId {
        VisibleCoinsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleCoinsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleCoinsTableHandle<'ctx> {
    type DeleteCallbackId = VisibleCoinsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleCoinsDeleteCallbackId {
        VisibleCoinsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleCoinsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisibleCoinsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibleCoinsTableHandle<'ctx> {
    type UpdateCallbackId = VisibleCoinsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleCoinsUpdateCallbackId {
        VisibleCoinsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleCoinsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VisibleCoinsTableHandle<'ctx> {
    type UpdateCallbackId = VisibleCoinsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleCoinsUpdateCallbackId {
        VisibleCoinsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleCoinsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `coin_key` unique index on the table `visible_coins`,
/// which allows point queries on the field of the same name
/// via the [`VisibleCoinsCoinKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_coins().coin_key().find(...)`.
pub struct VisibleCoinsCoinKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Coin, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibleCoinsTableHandle<'ctx> {
    /// Get a handle on the `coin_key` unique index on the table `visible_coins`.
    pub fn coin_key(&self) -> VisibleCoinsCoinKeyUnique<'ctx> {
        VisibleCoinsCoinKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("coin_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibleCoinsCoinKeyUnique<'ctx> {
    /// Find the subscribed row whose `coin_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Coin> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Coin>("visible_coins");
    _table.add_unique_constraint::<String>("coin_key", |row| &row.coin_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Coin>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Coin>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Coin`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_coinsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Coin`.
    fn visible_coins(&self) -> __sdk::__query_builder::Table<Coin>;
}

impl visible_coinsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_coins(&self) -> __sdk::__query_builder::Table<Coin> {
        __sdk::__query_builder::Table::new("visible_coins")
    }
}
