// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::room_game_type::RoomGame;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_room_games`.
///
/// Obtain a handle from the [`VisibleRoomGamesTableAccess::visible_room_games`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_room_games()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_room_games().on_insert(...)`.
pub struct VisibleRoomGamesTableHandle<'ctx> {
    imp: __sdk::TableHandle<RoomGame>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_room_games`.
pub struct VisibleRoomGamesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleRoomGamesTableAccessor {
    type Row = RoomGame;
    type Handle<'db> = VisibleRoomGamesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_room_games()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_room_games`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleRoomGamesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleRoomGamesTableHandle`], which mediates access to the table `visible_room_games`.
    fn visible_room_games(&self) -> VisibleRoomGamesTableHandle<'_>;
}

impl VisibleRoomGamesTableAccess for super::RemoteTables {
    fn visible_room_games(&self) -> VisibleRoomGamesTableHandle<'_> {
        VisibleRoomGamesTableHandle {
            imp: self.imp.get_table::<RoomGame>("visible_room_games"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleRoomGamesInsertCallbackId(__sdk::CallbackId);
pub struct VisibleRoomGamesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleRoomGamesTableHandle<'ctx> {
    type Row = RoomGame;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoomGame> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleRoomGamesTableHandle<'ctx> {
    type Row = RoomGame;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoomGame> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleRoomGamesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoomGamesInsertCallbackId {
        VisibleRoomGamesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleRoomGamesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleRoomGamesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoomGamesDeleteCallbackId {
        VisibleRoomGamesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleRoomGamesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleRoomGamesTableHandle<'ctx> {
    type InsertCallbackId = VisibleRoomGamesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoomGamesInsertCallbackId {
        VisibleRoomGamesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleRoomGamesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleRoomGamesTableHandle<'ctx> {
    type DeleteCallbackId = VisibleRoomGamesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoomGamesDeleteCallbackId {
        VisibleRoomGamesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleRoomGamesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisibleRoomGamesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibleRoomGamesTableHandle<'ctx> {
    type UpdateCallbackId = VisibleRoomGamesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleRoomGamesUpdateCallbackId {
        VisibleRoomGamesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleRoomGamesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VisibleRoomGamesTableHandle<'ctx> {
    type UpdateCallbackId = VisibleRoomGamesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleRoomGamesUpdateCallbackId {
        VisibleRoomGamesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleRoomGamesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `room_id` unique index on the table `visible_room_games`,
/// which allows point queries on the field of the same name
/// via the [`VisibleRoomGamesRoomIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_room_games().room_id().find(...)`.
pub struct VisibleRoomGamesRoomIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RoomGame, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibleRoomGamesTableHandle<'ctx> {
    /// Get a handle on the `room_id` unique index on the table `visible_room_games`.
    pub fn room_id(&self) -> VisibleRoomGamesRoomIdUnique<'ctx> {
        VisibleRoomGamesRoomIdUnique {
            imp: self.imp.get_unique_constraint::<String>("room_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibleRoomGamesRoomIdUnique<'ctx> {
    /// Find the subscribed row whose `room_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RoomGame> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RoomGame>("visible_room_games");
    _table.add_unique_constraint::<String>("room_id", |row| &row.room_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RoomGame>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RoomGame>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RoomGame`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_room_gamesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RoomGame`.
    fn visible_room_games(&self) -> __sdk::__query_builder::Table<RoomGame>;
}

impl visible_room_gamesQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_room_games(&self) -> __sdk::__query_builder::Table<RoomGame> {
        __sdk::__query_builder::Table::new("visible_room_games")
    }
}
