// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::card_pose_type::CardPose;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_card_poses`.
///
/// Obtain a handle from the [`VisibleCardPosesTableAccess::visible_card_poses`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_card_poses()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_card_poses().on_insert(...)`.
pub struct VisibleCardPosesTableHandle<'ctx> {
    imp: __sdk::TableHandle<CardPose>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_card_poses`.
pub struct VisibleCardPosesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleCardPosesTableAccessor {
    type Row = CardPose;
    type Handle<'db> = VisibleCardPosesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_card_poses()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_card_poses`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleCardPosesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleCardPosesTableHandle`], which mediates access to the table `visible_card_poses`.
    fn visible_card_poses(&self) -> VisibleCardPosesTableHandle<'_>;
}

impl VisibleCardPosesTableAccess for super::RemoteTables {
    fn visible_card_poses(&self) -> VisibleCardPosesTableHandle<'_> {
        VisibleCardPosesTableHandle {
            imp: self.imp.get_table::<CardPose>("visible_card_poses"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleCardPosesInsertCallbackId(__sdk::CallbackId);
pub struct VisibleCardPosesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleCardPosesTableHandle<'ctx> {
    type Row = CardPose;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CardPose> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleCardPosesTableHandle<'ctx> {
    type Row = CardPose;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CardPose> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleCardPosesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleCardPosesInsertCallbackId {
        VisibleCardPosesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleCardPosesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleCardPosesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleCardPosesDeleteCallbackId {
        VisibleCardPosesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleCardPosesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleCardPosesTableHandle<'ctx> {
    type InsertCallbackId = VisibleCardPosesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleCardPosesInsertCallbackId {
        VisibleCardPosesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleCardPosesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleCardPosesTableHandle<'ctx> {
    type DeleteCallbackId = VisibleCardPosesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleCardPosesDeleteCallbackId {
        VisibleCardPosesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleCardPosesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisibleCardPosesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibleCardPosesTableHandle<'ctx> {
    type UpdateCallbackId = VisibleCardPosesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleCardPosesUpdateCallbackId {
        VisibleCardPosesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleCardPosesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VisibleCardPosesTableHandle<'ctx> {
    type UpdateCallbackId = VisibleCardPosesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleCardPosesUpdateCallbackId {
        VisibleCardPosesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleCardPosesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `card_key` unique index on the table `visible_card_poses`,
/// which allows point queries on the field of the same name
/// via the [`VisibleCardPosesCardKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_card_poses().card_key().find(...)`.
pub struct VisibleCardPosesCardKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CardPose, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibleCardPosesTableHandle<'ctx> {
    /// Get a handle on the `card_key` unique index on the table `visible_card_poses`.
    pub fn card_key(&self) -> VisibleCardPosesCardKeyUnique<'ctx> {
        VisibleCardPosesCardKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("card_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibleCardPosesCardKeyUnique<'ctx> {
    /// Find the subscribed row whose `card_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<CardPose> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CardPose>("visible_card_poses");
    _table.add_unique_constraint::<String>("card_key", |row| &row.card_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CardPose>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CardPose>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CardPose`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_card_posesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CardPose`.
    fn visible_card_poses(&self) -> __sdk::__query_builder::Table<CardPose>;
}

impl visible_card_posesQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_card_poses(&self) -> __sdk::__query_builder::Table<CardPose> {
        __sdk::__query_builder::Table::new("visible_card_poses")
    }
}
