// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::revealed_card_type::RevealedCard;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_revealed_cards`.
///
/// Obtain a handle from the [`VisibleRevealedCardsTableAccess::visible_revealed_cards`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_revealed_cards()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_revealed_cards().on_insert(...)`.
pub struct VisibleRevealedCardsTableHandle<'ctx> {
    imp: __sdk::TableHandle<RevealedCard>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_revealed_cards`.
pub struct VisibleRevealedCardsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleRevealedCardsTableAccessor {
    type Row = RevealedCard;
    type Handle<'db> = VisibleRevealedCardsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_revealed_cards()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_revealed_cards`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleRevealedCardsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleRevealedCardsTableHandle`], which mediates access to the table `visible_revealed_cards`.
    fn visible_revealed_cards(&self) -> VisibleRevealedCardsTableHandle<'_>;
}

impl VisibleRevealedCardsTableAccess for super::RemoteTables {
    fn visible_revealed_cards(&self) -> VisibleRevealedCardsTableHandle<'_> {
        VisibleRevealedCardsTableHandle {
            imp: self.imp.get_table::<RevealedCard>("visible_revealed_cards"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleRevealedCardsInsertCallbackId(__sdk::CallbackId);
pub struct VisibleRevealedCardsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleRevealedCardsTableHandle<'ctx> {
    type Row = RevealedCard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RevealedCard> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleRevealedCardsTableHandle<'ctx> {
    type Row = RevealedCard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RevealedCard> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleRevealedCardsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRevealedCardsInsertCallbackId {
        VisibleRevealedCardsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleRevealedCardsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleRevealedCardsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRevealedCardsDeleteCallbackId {
        VisibleRevealedCardsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleRevealedCardsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleRevealedCardsTableHandle<'ctx> {
    type InsertCallbackId = VisibleRevealedCardsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRevealedCardsInsertCallbackId {
        VisibleRevealedCardsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleRevealedCardsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleRevealedCardsTableHandle<'ctx> {
    type DeleteCallbackId = VisibleRevealedCardsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRevealedCardsDeleteCallbackId {
        VisibleRevealedCardsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleRevealedCardsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisibleRevealedCardsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibleRevealedCardsTableHandle<'ctx> {
    type UpdateCallbackId = VisibleRevealedCardsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleRevealedCardsUpdateCallbackId {
        VisibleRevealedCardsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleRevealedCardsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VisibleRevealedCardsTableHandle<'ctx> {
    type UpdateCallbackId = VisibleRevealedCardsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleRevealedCardsUpdateCallbackId {
        VisibleRevealedCardsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleRevealedCardsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `card_key` unique index on the table `visible_revealed_cards`,
/// which allows point queries on the field of the same name
/// via the [`VisibleRevealedCardsCardKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_revealed_cards().card_key().find(...)`.
pub struct VisibleRevealedCardsCardKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RevealedCard, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibleRevealedCardsTableHandle<'ctx> {
    /// Get a handle on the `card_key` unique index on the table `visible_revealed_cards`.
    pub fn card_key(&self) -> VisibleRevealedCardsCardKeyUnique<'ctx> {
        VisibleRevealedCardsCardKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("card_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibleRevealedCardsCardKeyUnique<'ctx> {
    /// Find the subscribed row whose `card_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RevealedCard> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RevealedCard>("visible_revealed_cards");
    _table.add_unique_constraint::<String>("card_key", |row| &row.card_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RevealedCard>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RevealedCard>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RevealedCard`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_revealed_cardsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RevealedCard`.
    fn visible_revealed_cards(&self) -> __sdk::__query_builder::Table<RevealedCard>;
}

impl visible_revealed_cardsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_revealed_cards(&self) -> __sdk::__query_builder::Table<RevealedCard> {
        __sdk::__query_builder::Table::new("visible_revealed_cards")
    }
}
