// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::round_record_type::RoundRecord;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_rounds`.
///
/// Obtain a handle from the [`VisibleRoundsTableAccess::visible_rounds`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_rounds()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_rounds().on_insert(...)`.
pub struct VisibleRoundsTableHandle<'ctx> {
    imp: __sdk::TableHandle<RoundRecord>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_rounds`.
pub struct VisibleRoundsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleRoundsTableAccessor {
    type Row = RoundRecord;
    type Handle<'db> = VisibleRoundsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_rounds()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_rounds`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleRoundsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleRoundsTableHandle`], which mediates access to the table `visible_rounds`.
    fn visible_rounds(&self) -> VisibleRoundsTableHandle<'_>;
}

impl VisibleRoundsTableAccess for super::RemoteTables {
    fn visible_rounds(&self) -> VisibleRoundsTableHandle<'_> {
        VisibleRoundsTableHandle {
            imp: self.imp.get_table::<RoundRecord>("visible_rounds"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleRoundsInsertCallbackId(__sdk::CallbackId);
pub struct VisibleRoundsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleRoundsTableHandle<'ctx> {
    type Row = RoundRecord;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoundRecord> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleRoundsTableHandle<'ctx> {
    type Row = RoundRecord;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoundRecord> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleRoundsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoundsInsertCallbackId {
        VisibleRoundsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleRoundsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleRoundsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoundsDeleteCallbackId {
        VisibleRoundsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleRoundsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleRoundsTableHandle<'ctx> {
    type InsertCallbackId = VisibleRoundsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoundsInsertCallbackId {
        VisibleRoundsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleRoundsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleRoundsTableHandle<'ctx> {
    type DeleteCallbackId = VisibleRoundsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoundsDeleteCallbackId {
        VisibleRoundsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleRoundsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisibleRoundsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibleRoundsTableHandle<'ctx> {
    type UpdateCallbackId = VisibleRoundsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleRoundsUpdateCallbackId {
        VisibleRoundsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleRoundsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VisibleRoundsTableHandle<'ctx> {
    type UpdateCallbackId = VisibleRoundsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleRoundsUpdateCallbackId {
        VisibleRoundsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleRoundsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `round_key` unique index on the table `visible_rounds`,
/// which allows point queries on the field of the same name
/// via the [`VisibleRoundsRoundKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_rounds().round_key().find(...)`.
pub struct VisibleRoundsRoundKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RoundRecord, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibleRoundsTableHandle<'ctx> {
    /// Get a handle on the `round_key` unique index on the table `visible_rounds`.
    pub fn round_key(&self) -> VisibleRoundsRoundKeyUnique<'ctx> {
        VisibleRoundsRoundKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("round_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibleRoundsRoundKeyUnique<'ctx> {
    /// Find the subscribed row whose `round_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<RoundRecord> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RoundRecord>("visible_rounds");
    _table.add_unique_constraint::<String>("round_key", |row| &row.round_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RoundRecord>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RoundRecord>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RoundRecord`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_roundsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RoundRecord`.
    fn visible_rounds(&self) -> __sdk::__query_builder::Table<RoundRecord>;
}

impl visible_roundsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_rounds(&self) -> __sdk::__query_builder::Table<RoundRecord> {
        __sdk::__query_builder::Table::new("visible_rounds")
    }
}
