[package]
name = "poche-xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
poche-check = { path = "../poche-check" }
poche-conformance = { path = "../poche-conformance" }
poche-native-tools = { path = "../poche-native-tools" }
poche-oracle-rust = { path = "../poche-oracle-rust" }

[lints]
workspace = true
