[package]
name = "poche-puppet"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
blake3.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
poche-capture = { path = "../poche-capture" }
poche-native-ui = { path = "../poche-native-ui" }
poche-player-client = { path = "../poche-player-client" }
poche-protocol = { path = "../poche-protocol" }
poche-runtime = { path = "../poche-runtime" }
poche-session = { path = "../poche-session" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
