[package]
name = "poche-environment"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
poche-oracle-rust = { path = "../poche-oracle-rust" }

[lints]
workspace = true
