[package]
name = "poche-veilid"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = []
veilid = ["dep:veilid-core"]
insecure-development = []

[dependencies]
blake3.workspace = true
curve25519-dalek.workspace = true
data-encoding.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
poche-protocol = { path = "../poche-protocol" }
serde.workspace = true
serde_json.workspace = true
veilid-core = { workspace = true, optional = true }

[dev-dependencies]
poche-runtime = { path = "../poche-runtime" }
poche-session = { path = "../poche-session" }
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
