[package]
name = "poche-check"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
blake3 = "=1.8.5"
poche-model = { path = "../poche-model" }
poche-interchange = { path = "../poche-interchange" }
poche-oracle-rust = { path = "../poche-oracle-rust" }
poche-spatial = { path = "../poche-spatial" }
phon.workspace = true

[lints]
workspace = true
