[package]
name = "poche-check"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
poche-model = { path = "../poche-model" }
poche-interchange = { path = "../poche-interchange" }
phon.workspace = true

[lints]
workspace = true
