[package]
name = "poche-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
blake3.workspace = true
poche-environment = { path = "../poche-environment" }
poche-oracle-rust = { path = "../poche-oracle-rust" }
poche-protocol = { path = "../poche-protocol" }
poche-session = { path = "../poche-session" }
poche-spatial = { path = "../poche-spatial" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
