[package]
name = "poche-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
build = "build.rs"

[[bin]]
name = "poche"
path = "src/main.rs"

[dependencies]
zeroize.workspace = true
blake3.workspace = true
eyre = "=0.6.12"
facet.workspace = true
figue.workspace = true
getrandom.workspace = true
poche-domain = { path = "../poche-domain" }
poche-capture = { path = "../poche-capture" }
poche-native-ui = { path = "../poche-native-ui" }
poche-player-client = { path = "../poche-player-client", features = ["http", "protected-store"] }
poche-protocol = { path = "../poche-protocol" }
poche-puppet = { path = "../poche-puppet" }
poche-runtime = { path = "../poche-runtime" }
poche-veilid = { path = "../poche-veilid", features = ["device-service"] }
veilid-core.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
teamy-cancellation = { git = "https://github.com/TeamDman/teamy-cancellation.git", tag = "v0.3.1", default-features = false, features = ["ctrlc", "tracing"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
