[package]
name = "poche-model"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
facet.workspace = true
poche-domain = { path = "../poche-domain" }
poche-formal = { path = "../poche-formal" }

[dev-dependencies]
phon.workspace = true
poche-oracle-rust = { path = "../poche-oracle-rust" }
proptest = "=1.11.0"

[lints]
workspace = true
