// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Renderer-neutral `SpacetimeDB` client and generated Poche module bindings.

#![allow(
    clippy::missing_errors_doc,
    clippy::missing_panics_doc,
    clippy::wildcard_imports
)]

// Generated by `spacetime generate`; keep it reproducible instead of hand-editing it
// to satisfy lints that are stricter than the generator's own output.
#[allow(clippy::all, clippy::pedantic, missing_docs)]
pub mod module_bindings;

use module_bindings::*;
use spacetimedb_sdk::{DbContext, Identity, Table, TableWithPrimaryKey, credentials};
use std::fmt;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Condvar, Mutex, mpsc};
use std::thread::JoinHandle;
use std::time::{Duration, Instant};

pub const DEFAULT_URI: &str = "http://127.0.0.1:3000";
pub const DEFAULT_DATABASE: &str = "poche-desktop-v1";

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ClientConfig {
    pub uri: String,
    pub database: String,
    /// Immutable local account identifier used only to locate a protected token.
    pub account_id: String,
}

impl ClientConfig {
    #[must_use]
    pub fn local(account_id: impl Into<String>) -> Self {
        Self {
            uri: std::env::var("POCHE_SPACETIMEDB_URI").unwrap_or_else(|_| DEFAULT_URI.into()),
            database: std::env::var("POCHE_SPACETIMEDB_DATABASE")
                .unwrap_or_else(|_| DEFAULT_DATABASE.into()),
            account_id: account_id.into(),
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RoomCapability {
    pub room_id: String,
    pub join_code: String,
}

impl RoomCapability {
    pub fn generate() -> Result<Self, ClientError> {
        let mut bytes = [0_u8; 24];
        getrandom::fill(&mut bytes).map_err(|error| ClientError::Random(error.to_string()))?;
        let room_id = format!("room-{}", encode_hex(&bytes[..16], false));
        let encoded = encode_hex(&bytes[16..], true);
        let join_code = format!(
            "PCH-{}-{}-{}-{}",
            &encoded[0..4],
            &encoded[4..8],
            &encoded[8..12],
            &encoded[12..16]
        );
        Ok(Self { room_id, join_code })
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ConnectionState {
    Connecting,
    Connected,
    Ready,
    Disconnected,
    Failed(String),
}

#[derive(Clone, Debug)]
pub enum ClientEvent {
    Connected {
        identity: String,
    },
    Ready,
    ModelChanged,
    CommandFinished {
        request_id: u64,
        operation: &'static str,
        elapsed: Duration,
        result: Result<(), String>,
    },
    Disconnected {
        reason: Option<String>,
    },
    Error(String),
}

#[derive(Clone, Debug, Default, PartialEq)]
pub struct ClientSnapshot {
    pub identity: Option<String>,
    pub room_capability: Option<RoomCapability>,
    pub rooms: Vec<RoomView>,
    pub members: Vec<MemberView>,
    pub hand: Vec<HandCardView>,
    pub card_poses: Vec<CardPoseView>,
    /// Public physical coins in this viewer's active room, never card secrets.
    pub coins: Vec<CoinView>,
    pub game: Option<GameView>,
    /// Completed score-sheet rows, ordered by round, without hidden card faces.
    pub rounds: Vec<RoundView>,
    pub revealed_cards: Vec<RevealedCardView>,
    pub activity: Vec<ActivityView>,
}

impl ClientSnapshot {
    /// Unpaid opening ante or scored missed bids; actual bowl coins are the payments.
    #[must_use]
    pub fn payment_due(&self, seat: u8) -> u32 {
        let index = usize::from(seat);
        if index >= 2 {
            return 0;
        }
        let mut expected = 25
            + self
                .rounds
                .iter()
                .map(|round| round.payment_cents[index])
                .sum::<u32>();
        if let Some(game) = self.game.as_ref().filter(|game| {
            game.phase == "scoring"
                && !self
                    .rounds
                    .iter()
                    .any(|round| round.round_index == game.round_index)
        }) && game.bids[index].is_some_and(|bid| bid != game.tricks_won[index])
        {
            expected += 10;
        }
        let paid = self
            .coins
            .iter()
            .filter(|coin| coin.owner_seat == Some(seat) && coin.container == "bowl")
            .map(|coin| u32::from(coin.denomination_cents))
            .sum::<u32>();
        expected.saturating_sub(paid)
    }
    #[must_use]
    pub fn room_id(&self) -> Option<&str> {
        self.rooms.first().map(|room| room.room_id.as_str())
    }

    #[must_use]
    pub fn own_seat(&self) -> Option<u8> {
        let identity = self.identity.as_deref()?;
        self.members
            .iter()
            .find(|member| member.identity == identity)
            .and_then(|member| member.seat)
    }

    /// Return the face this exact viewer is authorized to render.
    #[must_use]
    pub fn visible_card_face(&self, card_key: &str) -> Option<&str> {
        self.hand
            .iter()
            .find(|card| card.card_key == card_key)
            .map(|card| card.face.as_str())
            .or_else(|| {
                self.revealed_cards
                    .iter()
                    .find(|card| card.card_key == card_key)
                    .map(|card| card.face.as_str())
            })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct RoomView {
    pub room_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct MemberView {
    pub identity: String,
    pub display_name: String,
    pub seat: Option<u8>,
    pub connected: bool,
    pub is_self: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct HandCardView {
    pub card_key: String,
    pub card_id: String,
    pub face: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CardPoseView {
    pub card_key: String,
    pub card_id: String,
    pub owner: String,
    pub owner_seat: u8,
    pub logical_location: String,
    pub position_mm: [i32; 3],
    pub rotation_mdeg: [i32; 3],
    pub sequence: u64,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CoinView {
    pub coin_key: String,
    pub coin_id: String,
    pub owner: String,
    pub owner_seat: Option<u8>,
    pub is_own: bool,
    pub denomination_cents: u8,
    /// Authoritative logical container: jar, lid or bowl. A pose update alone
    /// does not change this value or contribute an ante.
    pub container: String,
    pub position_mm: [i32; 3],
    pub sequence: u64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct RevealedCardView {
    pub card_key: String,
    pub face: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct ActivityView {
    pub sequence: u64,
    pub kind: String,
    pub summary: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct GameView {
    pub phase: String,
    pub actor_seat: Option<u8>,
    pub dealer_seat: Option<u8>,
    pub round_index: u16,
    pub hand_size: u8,
    pub hand_counts: [u8; 2],
    pub bids: [Option<u8>; 2],
    pub trick_count: u8,
    pub trick_seats: [Option<u8>; 2],
    pub trick_cards: [Option<u8>; 2],
    pub tricks_won: [u8; 2],
    pub scores: [u16; 2],
    pub pot_cents: u32,
    pub trump: Option<u8>,
    pub action_count: u64,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RoundView {
    pub round_index: u16,
    pub dealer_seat: u8,
    pub hand_size: u8,
    pub bids: [u8; 2],
    pub tricks_won: [u8; 2],
    pub points: [u16; 2],
    pub totals: [u16; 2],
    pub payment_cents: [u32; 2],
}

#[derive(Debug)]
pub enum ClientError {
    Connect(String),
    Timeout(String),
    Credentials(String),
    Random(String),
    Request(String),
}

impl fmt::Display for ClientError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Connect(message) => write!(formatter, "connection failed: {message}"),
            Self::Timeout(message) => write!(formatter, "timed out: {message}"),
            Self::Credentials(message) => write!(formatter, "credential error: {message}"),
            Self::Random(message) => write!(formatter, "randomness unavailable: {message}"),
            Self::Request(message) => write!(formatter, "request failed: {message}"),
        }
    }
}

impl std::error::Error for ClientError {}

#[derive(Debug)]
struct Lifecycle {
    state: ConnectionState,
    identity: Option<String>,
}

struct ClientInner {
    connection: DbConnection,
    worker: Mutex<Option<JoinHandle<()>>>,
    lifecycle: Arc<(Mutex<Lifecycle>, Condvar)>,
    event_tx: mpsc::Sender<ClientEvent>,
    event_rx: Mutex<mpsc::Receiver<ClientEvent>>,
    next_request: AtomicU64,
}

impl Drop for ClientInner {
    fn drop(&mut self) {
        let _ = self.connection.disconnect();
        if let Some(worker) = self.worker.lock().expect("worker mutex poisoned").take() {
            let _ = worker.join();
        }
    }
}

#[derive(Clone)]
pub struct PocheClient {
    inner: Arc<ClientInner>,
}

impl PocheClient {
    pub fn connect(config: ClientConfig, timeout: Duration) -> Result<Self, ClientError> {
        let (event_tx, event_rx) = mpsc::channel();
        let lifecycle = Arc::new((
            Mutex::new(Lifecycle {
                state: ConnectionState::Connecting,
                identity: None,
            }),
            Condvar::new(),
        ));
        let credential_key = credential_key(&config);
        let token = credentials::File::new(&credential_key)
            .load()
            .map_err(|error| ClientError::Credentials(error.to_string()))?;

        let connected_lifecycle = Arc::clone(&lifecycle);
        let connected_tx = event_tx.clone();
        let connected_credential_key = credential_key.clone();
        let error_lifecycle = Arc::clone(&lifecycle);
        let error_tx = event_tx.clone();
        let disconnected_lifecycle = Arc::clone(&lifecycle);
        let disconnected_tx = event_tx.clone();

        let connection = DbConnection::builder()
            .on_connect(move |_ctx, identity: Identity, token: &str| {
                if let Err(error) = credentials::File::new(&connected_credential_key).save(token) {
                    let _ = connected_tx.send(ClientEvent::Error(format!(
                        "failed to save profile credential: {error}"
                    )));
                }
                let identity = identity.to_hex().to_string();
                let (state, wake) = &*connected_lifecycle;
                let mut state = state.lock().expect("lifecycle mutex poisoned");
                state.state = ConnectionState::Connected;
                state.identity = Some(identity.clone());
                wake.notify_all();
                let _ = connected_tx.send(ClientEvent::Connected { identity });
            })
            .on_connect_error(move |_ctx, error| {
                let message = error.to_string();
                let (state, wake) = &*error_lifecycle;
                state.lock().expect("lifecycle mutex poisoned").state =
                    ConnectionState::Failed(message.clone());
                wake.notify_all();
                let _ = error_tx.send(ClientEvent::Error(message));
            })
            .on_disconnect(move |_ctx, error| {
                let reason = error.map(|error| error.to_string());
                let (state, wake) = &*disconnected_lifecycle;
                state.lock().expect("lifecycle mutex poisoned").state =
                    ConnectionState::Disconnected;
                wake.notify_all();
                let _ = disconnected_tx.send(ClientEvent::Disconnected { reason });
            })
            .with_token(token)
            .with_database_name(config.database)
            .with_uri(config.uri)
            .build()
            .map_err(|error| ClientError::Connect(error.to_string()))?;

        register_change_callbacks(&connection, event_tx.clone());
        subscribe(&connection, Arc::clone(&lifecycle), event_tx.clone());
        let worker = connection.run_threaded();
        let client = Self {
            inner: Arc::new(ClientInner {
                connection,
                worker: Mutex::new(Some(worker)),
                lifecycle,
                event_tx,
                event_rx: Mutex::new(event_rx),
                next_request: AtomicU64::new(1),
            }),
        };
        client.wait_until_ready(timeout)?;
        Ok(client)
    }

    pub fn wait_until_ready(&self, timeout: Duration) -> Result<(), ClientError> {
        let deadline = Instant::now() + timeout;
        let (state, wake) = &*self.inner.lifecycle;
        let mut state = state.lock().expect("lifecycle mutex poisoned");
        loop {
            match &state.state {
                ConnectionState::Ready => return Ok(()),
                ConnectionState::Failed(message) => {
                    return Err(ClientError::Connect(message.clone()));
                }
                ConnectionState::Disconnected => {
                    return Err(ClientError::Connect("disconnected before ready".into()));
                }
                ConnectionState::Connecting | ConnectionState::Connected => {}
            }
            let now = Instant::now();
            if now >= deadline {
                return Err(ClientError::Timeout(
                    "waiting for initial subscription".into(),
                ));
            }
            let (new_state, wait) = wake
                .wait_timeout(state, deadline.saturating_duration_since(now))
                .expect("lifecycle mutex poisoned while waiting");
            state = new_state;
            if wait.timed_out() && !matches!(state.state, ConnectionState::Ready) {
                return Err(ClientError::Timeout(
                    "waiting for initial subscription".into(),
                ));
            }
        }
    }

    #[must_use]
    pub fn connection_state(&self) -> ConnectionState {
        self.inner
            .lifecycle
            .0
            .lock()
            .expect("lifecycle mutex poisoned")
            .state
            .clone()
    }

    #[must_use]
    pub fn snapshot(&self) -> ClientSnapshot {
        snapshot_from(&self.inner.connection)
    }

    #[must_use]
    pub fn drain_events(&self) -> Vec<ClientEvent> {
        let receiver = self
            .inner
            .event_rx
            .lock()
            .expect("event receiver mutex poisoned");
        receiver.try_iter().collect()
    }

    pub fn create_room(&self, display_name: String) -> Result<RoomCapability, ClientError> {
        let capability = RoomCapability::generate()?;
        let request_id = self.next_request();
        let started = Instant::now();
        let tx = self.inner.event_tx.clone();
        self.inner
            .connection
            .reducers
            .create_room_then(
                capability.room_id.clone(),
                capability.join_code.clone(),
                display_name,
                move |_ctx, result| finish_command(&tx, request_id, "create_room", started, result),
            )
            .map_err(|error| ClientError::Request(error.to_string()))?;
        Ok(capability)
    }

    pub fn join_room(&self, join_code: String, display_name: String) -> Result<u64, ClientError> {
        if !valid_join_code(&join_code) {
            return Err(ClientError::Request(
                "join code has an invalid shape".into(),
            ));
        }
        let request_id = self.next_request();
        let started = Instant::now();
        let tx = self.inner.event_tx.clone();
        self.inner
            .connection
            .reducers
            .join_room_then(join_code, display_name, move |_ctx, result| {
                finish_command(&tx, request_id, "join_room", started, result);
            })
            .map_err(|error| ClientError::Request(error.to_string()))?;
        Ok(request_id)
    }

    pub fn take_seat(&self, room_id: String, seat: u8) -> Result<u64, ClientError> {
        let request_id = self.next_request();
        let started = Instant::now();
        let tx = self.inner.event_tx.clone();
        self.inner
            .connection
            .reducers
            .take_seat_then(room_id, seat, move |_ctx, result| {
                finish_command(&tx, request_id, "take_seat", started, result);
            })
            .map_err(|error| ClientError::Request(error.to_string()))?;
        Ok(request_id)
    }

    pub fn release_seat(&self, room_id: String) -> Result<u64, ClientError> {
        let request_id = self.next_request();
        let started = Instant::now();
        let tx = self.inner.event_tx.clone();
        self.inner
            .connection
            .reducers
            .release_seat_then(room_id, move |_ctx, result| {
                finish_command(&tx, request_id, "release_seat", started, result);
            })
            .map_err(|error| ClientError::Request(error.to_string()))?;
        Ok(request_id)
    }

    #[allow(clippy::too_many_arguments)]
    pub fn set_card_pose(
        &self,
        room_id: String,
        card_id: String,
        sequence: u64,
        position_mm: [i32; 3],
        rotation_mdeg: [i32; 3],
    ) -> Result<u64, ClientError> {
        let request_id = self.next_request();
        let started = Instant::now();
        let tx = self.inner.event_tx.clone();
        self.inner
            .connection
            .reducers
            .set_card_pose_then(
                room_id,
                card_id,
                sequence,
                position_mm[0],
                position_mm[1],
                position_mm[2],
                rotation_mdeg[0],
                rotation_mdeg[1],
                rotation_mdeg[2],
                move |_ctx, result| {
                    finish_command(&tx, request_id, "set_card_pose", started, result);
                },
            )
            .map_err(|error| ClientError::Request(error.to_string()))?;
        Ok(request_id)
    }

    pub fn bid(&self, room_id: String, tricks: u8) -> Result<u64, ClientError> {
        let request_id = self.next_request();
        let started = Instant::now();
        let tx = self.inner.event_tx.clone();
        self.inner
            .connection
            .reducers
            .bid_then(room_id, tricks, move |_ctx, result| {
                finish_command(&tx, request_id, "bid", started, result);
            })
            .map_err(|error| ClientError::Request(error.to_string()))?;
        Ok(request_id)
    }

    pub fn deal_next_round(&self, room_id: String) -> Result<u64, ClientError> {
        let request_id = self.next_request();
        let started = Instant::now();
        let tx = self.inner.event_tx.clone();
        self.inner
            .connection
            .reducers
            .deal_next_round_then(room_id, move |_ctx, result| {
                finish_command(&tx, request_id, "deal_next_round", started, result);
            })
            .map_err(|error| ClientError::Request(error.to_string()))?;
        Ok(request_id)
    }

    /// Preview a physical move or commit a container transfer on release.
    /// Ownership, contribution amounts and container legality remain server
    /// decisions; successfully queueing this request is not an acceptance.
    #[allow(clippy::too_many_arguments)]
    pub fn move_coin(
        &self,
        room_id: String,
        coin_id: String,
        sequence: u64,
        container: String,
        position_mm: [i32; 3],
        commit: bool,
    ) -> Result<u64, ClientError> {
        let request_id = self.next_request();
        let started = Instant::now();
        let tx = self.inner.event_tx.clone();
        self.inner
            .connection
            .reducers
            .move_coin_then(
                room_id,
                coin_id,
                sequence,
                container,
                position_mm[0],
                position_mm[1],
                position_mm[2],
                commit,
                move |_ctx, result| finish_command(&tx, request_id, "move_coin", started, result),
            )
            .map_err(|error| ClientError::Request(error.to_string()))?;
        Ok(request_id)
    }

    pub fn play_card(&self, room_id: String, card_id: String) -> Result<u64, ClientError> {
        let request_id = self.next_request();
        let started = Instant::now();
        let tx = self.inner.event_tx.clone();
        self.inner
            .connection
            .reducers
            .play_card_then(room_id, card_id, move |_ctx, result| {
                finish_command(&tx, request_id, "play_card", started, result);
            })
            .map_err(|error| ClientError::Request(error.to_string()))?;
        Ok(request_id)
    }

    pub fn leave_room(&self, room_id: String) -> Result<u64, ClientError> {
        let request_id = self.next_request();
        let started = Instant::now();
        let tx = self.inner.event_tx.clone();
        self.inner
            .connection
            .reducers
            .leave_room_then(room_id, move |_ctx, result| {
                finish_command(&tx, request_id, "leave_room", started, result);
            })
            .map_err(|error| ClientError::Request(error.to_string()))?;
        Ok(request_id)
    }

    fn next_request(&self) -> u64 {
        self.inner.next_request.fetch_add(1, Ordering::Relaxed)
    }
}

fn register_change_callbacks(connection: &DbConnection, event_tx: mpsc::Sender<ClientEvent>) {
    let tx = event_tx.clone();
    connection.db.my_room_capability().on_insert(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection
        .db
        .my_room_capability()
        .on_update(move |_, _, _| {
            let _ = tx.send(ClientEvent::ModelChanged);
        });
    let tx = event_tx.clone();
    connection.db.my_room_capability().on_delete(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.my_rooms().on_insert(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.my_rooms().on_delete(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.room_members().on_insert(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.room_members().on_update(move |_, _, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.room_members().on_delete(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.my_hand().on_insert(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.my_hand().on_delete(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.visible_card_poses().on_insert(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection
        .db
        .visible_card_poses()
        .on_update(move |_, _, _| {
            let _ = tx.send(ClientEvent::ModelChanged);
        });
    let tx = event_tx.clone();
    connection.db.visible_card_poses().on_delete(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.visible_room_games().on_insert(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection
        .db
        .visible_room_games()
        .on_update(move |_, _, _| {
            let _ = tx.send(ClientEvent::ModelChanged);
        });
    let tx = event_tx.clone();
    connection.db.visible_room_games().on_delete(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection
        .db
        .visible_revealed_cards()
        .on_insert(move |_, _| {
            let _ = tx.send(ClientEvent::ModelChanged);
        });
    let tx = event_tx.clone();
    connection
        .db
        .visible_revealed_cards()
        .on_delete(move |_, _| {
            let _ = tx.send(ClientEvent::ModelChanged);
        });
    let tx = event_tx.clone();
    connection
        .db
        .visible_revealed_cards()
        .on_update(move |_, _, _| {
            let _ = tx.send(ClientEvent::ModelChanged);
        });
    register_coin_callbacks(connection, event_tx.clone());
    register_round_callbacks(connection, event_tx.clone());
    register_activity_callbacks(connection, event_tx);
}

fn register_round_callbacks(connection: &DbConnection, event_tx: mpsc::Sender<ClientEvent>) {
    let tx = event_tx.clone();
    connection.db.visible_rounds().on_insert(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.visible_rounds().on_update(move |_, _, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    connection.db.visible_rounds().on_delete(move |_, _| {
        let _ = event_tx.send(ClientEvent::ModelChanged);
    });
}

fn register_coin_callbacks(connection: &DbConnection, event_tx: mpsc::Sender<ClientEvent>) {
    let tx = event_tx.clone();
    connection.db.visible_coins().on_insert(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.visible_coins().on_update(move |_, _, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    connection.db.visible_coins().on_delete(move |_, _| {
        let _ = event_tx.send(ClientEvent::ModelChanged);
    });
}

fn register_activity_callbacks(connection: &DbConnection, event_tx: mpsc::Sender<ClientEvent>) {
    let tx = event_tx.clone();
    connection.db.visible_activity().on_insert(move |_, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    let tx = event_tx.clone();
    connection.db.visible_activity().on_update(move |_, _, _| {
        let _ = tx.send(ClientEvent::ModelChanged);
    });
    connection.db.visible_activity().on_delete(move |_, _| {
        let _ = event_tx.send(ClientEvent::ModelChanged);
    });
}

fn subscribe(
    connection: &DbConnection,
    lifecycle: Arc<(Mutex<Lifecycle>, Condvar)>,
    event_tx: mpsc::Sender<ClientEvent>,
) {
    let ready_tx = event_tx.clone();
    connection
        .subscription_builder()
        .on_applied(move |_| {
            let (state, wake) = &*lifecycle;
            state.lock().expect("lifecycle mutex poisoned").state = ConnectionState::Ready;
            wake.notify_all();
            let _ = ready_tx.send(ClientEvent::Ready);
        })
        .on_error(move |_ctx, error| {
            let _ = event_tx.send(ClientEvent::Error(format!("subscription failed: {error}")));
        })
        .add_query(|query| query.from.my_room_capability())
        .add_query(|query| query.from.my_rooms())
        .add_query(|query| query.from.room_members())
        .add_query(|query| query.from.my_hand())
        .add_query(|query| query.from.visible_card_poses())
        .add_query(|query| query.from.visible_coins())
        .add_query(|query| query.from.visible_room_games())
        .add_query(|query| query.from.visible_rounds())
        .add_query(|query| query.from.visible_revealed_cards())
        .add_query(|query| query.from.visible_activity())
        .subscribe();
}

#[allow(
    clippy::too_many_lines,
    reason = "One atomic projection of all sender-scoped SDK tables"
)]
fn snapshot_from(context: &DbConnection) -> ClientSnapshot {
    let identity = context
        .try_identity()
        .map(|identity| identity.to_hex().to_string());
    let room_capability = room_capability_from(context);
    let rooms = context
        .db
        .my_rooms()
        .iter()
        .map(|room| RoomView {
            room_id: room.room_id,
        })
        .collect::<Vec<_>>();
    let members = member_views(context.db.room_members().iter(), identity.as_deref());
    let mut hand = context
        .db
        .my_hand()
        .iter()
        .map(|card| HandCardView {
            card_key: card.card_key,
            card_id: card.card_id,
            face: card.face,
        })
        .collect::<Vec<_>>();
    hand.sort_by(|left, right| left.card_key.cmp(&right.card_key));
    let mut card_poses = context
        .db
        .visible_card_poses()
        .iter()
        .map(|pose| CardPoseView {
            card_key: pose.card_key,
            card_id: pose.card_id,
            owner: pose.owner.to_hex().to_string(),
            owner_seat: pose.owner_seat,
            logical_location: pose.logical_location,
            position_mm: [pose.x_mm, pose.y_mm, pose.z_mm],
            rotation_mdeg: [pose.rx_mdeg, pose.ry_mdeg, pose.rz_mdeg],
            sequence: pose.sequence,
        })
        .collect::<Vec<_>>();
    card_poses.sort_by(|left, right| left.card_key.cmp(&right.card_key));
    let game = context
        .db
        .visible_room_games()
        .iter()
        .next()
        .map(|game| GameView {
            phase: game.phase,
            actor_seat: game.actor_seat,
            dealer_seat: game.dealer_seat,
            round_index: game.round_index,
            hand_size: game.hand_size,
            hand_counts: [game.hand_count_0, game.hand_count_1],
            bids: [game.bid_0, game.bid_1],
            trick_count: game.trick_count,
            trick_seats: [game.trick_seat_0, game.trick_seat_1],
            trick_cards: [game.trick_card_0, game.trick_card_1],
            tricks_won: [game.tricks_won_0, game.tricks_won_1],
            scores: [game.score_0, game.score_1],
            pot_cents: game.pot_cents,
            trump: game.trump,
            action_count: game.action_count,
        });
    let mut revealed_cards = context
        .db
        .visible_revealed_cards()
        .iter()
        .map(|card| RevealedCardView {
            card_key: card.card_key,
            face: card.face,
        })
        .collect::<Vec<_>>();
    revealed_cards.sort_by(|left, right| left.card_key.cmp(&right.card_key));
    let activity = activity_from(context);
    let mut rounds = context
        .db
        .visible_rounds()
        .iter()
        .filter(|row| rooms.iter().any(|room| room.room_id == row.room_id))
        .filter_map(|row| {
            Some(RoundView {
                round_index: row.round_index,
                dealer_seat: row.dealer_seat,
                hand_size: row.hand_size,
                bids: row.bids.try_into().ok()?,
                tricks_won: row.tricks_won.try_into().ok()?,
                points: row.points.try_into().ok()?,
                totals: row.totals.try_into().ok()?,
                payment_cents: row.payment_cents.try_into().ok()?,
            })
        })
        .collect::<Vec<_>>();
    rounds.sort_by_key(|row| row.round_index);
    let coins = coin_views(
        context.db.visible_coins().iter(),
        &rooms,
        &members,
        identity.as_deref(),
    );
    ClientSnapshot {
        identity,
        room_capability,
        rooms,
        members,
        hand,
        card_poses,
        coins,
        game,
        rounds,
        revealed_cards,
        activity,
    }
}

fn member_views(rows: impl IntoIterator<Item = Member>, identity: Option<&str>) -> Vec<MemberView> {
    let mut members = rows
        .into_iter()
        .map(|member| {
            let member_identity = member.identity.to_hex().to_string();
            MemberView {
                is_self: identity == Some(member_identity.as_str()),
                identity: member_identity,
                display_name: member.display_name,
                seat: member.seat,
                connected: member.connected,
            }
        })
        .collect::<Vec<_>>();
    members.sort_by(|left, right| left.identity.cmp(&right.identity));
    members
}

fn coin_views(
    rows: impl IntoIterator<Item = Coin>,
    rooms: &[RoomView],
    members: &[MemberView],
    identity: Option<&str>,
) -> Vec<CoinView> {
    let mut coins = rows
        .into_iter()
        // The sender-scoped server view is the security boundary. This local
        // filter additionally prevents stale previous-room cache rows being
        // displayed while independent room/view deletion callbacks settle.
        .filter(|coin| rooms.iter().any(|room| room.room_id == coin.room_id))
        .map(|coin| {
            let owner = coin.owner.to_hex().to_string();
            CoinView {
                owner_seat: members
                    .iter()
                    .find(|member| member.identity == owner)
                    .and_then(|member| member.seat),
                is_own: identity == Some(owner.as_str()),
                owner,
                coin_key: coin.coin_key,
                coin_id: coin.coin_id,
                denomination_cents: coin.denomination_cents,
                container: coin.container,
                position_mm: [coin.x_mm, coin.y_mm, coin.z_mm],
                sequence: coin.sequence,
            }
        })
        .collect::<Vec<_>>();
    coins.sort_by(|left, right| left.coin_key.cmp(&right.coin_key));
    coins
}

fn activity_from(context: &DbConnection) -> Vec<ActivityView> {
    let mut activity = context
        .db
        .visible_activity()
        .iter()
        .map(|event| ActivityView {
            sequence: event.sequence,
            kind: event.kind,
            summary: event.summary,
        })
        .collect::<Vec<_>>();
    activity.sort_by_key(|event| event.sequence);
    activity
}

fn room_capability_from(context: &DbConnection) -> Option<RoomCapability> {
    context
        .db
        .my_room_capability()
        .iter()
        .next()
        .map(|capability| RoomCapability {
            room_id: capability.room_id,
            join_code: capability.join_code,
        })
}

fn finish_command<RemoteError: fmt::Display>(
    tx: &mpsc::Sender<ClientEvent>,
    request_id: u64,
    operation: &'static str,
    started: Instant,
    result: Result<Result<(), String>, RemoteError>,
) {
    let result = match result {
        Ok(result) => result,
        Err(error) => Err(error.to_string()),
    };
    let _ = tx.send(ClientEvent::CommandFinished {
        request_id,
        operation,
        elapsed: started.elapsed(),
        result,
    });
}

fn credential_key(config: &ClientConfig) -> String {
    let account = blake3::hash(config.account_id.as_bytes()).to_hex();
    if config.uri.trim_end_matches('/') == DEFAULT_URI && config.database == DEFAULT_DATABASE {
        return format!("poche-spacetimedb-{}", &account.as_str()[..32]);
    }
    let scope = blake3::hash(
        format!("{}\0{}", config.uri.trim_end_matches('/'), config.database).as_bytes(),
    )
    .to_hex();
    format!(
        "poche-spacetimedb-{}-{}",
        &scope.as_str()[..16],
        &account.as_str()[..32]
    )
}

fn encode_hex(bytes: &[u8], uppercase: bool) -> String {
    const LOWER: &[u8; 16] = b"0123456789abcdef";
    const UPPER: &[u8; 16] = b"0123456789ABCDEF";
    let digits = if uppercase { UPPER } else { LOWER };
    let mut result = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        result.push(char::from(digits[usize::from(byte >> 4)]));
        result.push(char::from(digits[usize::from(byte & 0x0f)]));
    }
    result
}

#[must_use]
pub fn valid_join_code(value: &str) -> bool {
    let bytes = value.as_bytes();
    bytes.len() == 23
        && bytes.starts_with(b"PCH-")
        && [3, 8, 13, 18].into_iter().all(|index| bytes[index] == b'-')
        && bytes.iter().enumerate().all(|(index, byte)| {
            index < 4 || [8, 13, 18].contains(&index) || byte.is_ascii_hexdigit()
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn repeat_misses_owe_new_dimes_without_charging_the_ante_again() {
        let round = RoundView {
            round_index: 0,
            dealer_seat: 0,
            hand_size: 1,
            bids: [0, 0],
            tricks_won: [1, 0],
            points: [0, 10],
            totals: [0, 10],
            payment_cents: [10, 0],
        };
        let mut snapshot = ClientSnapshot {
            rounds: vec![round.clone()],
            ..Default::default()
        };
        let coin = CoinView {
            coin_key: "q".into(),
            coin_id: "q".into(),
            owner: "alice".into(),
            owner_seat: Some(0),
            is_own: true,
            denomination_cents: 25,
            container: "bowl".into(),
            position_mm: [0; 3],
            sequence: 1,
        };
        snapshot.coins.push(coin.clone());
        assert_eq!(snapshot.payment_due(0), 10);
        snapshot.coins.push(CoinView {
            denomination_cents: 10,
            coin_id: "d-1".into(),
            ..coin.clone()
        });
        assert_eq!(snapshot.payment_due(0), 0);
        snapshot.rounds.push(RoundView {
            round_index: 1,
            ..round
        });
        assert_eq!(snapshot.payment_due(0), 10);
        snapshot.coins.push(CoinView {
            denomination_cents: 10,
            coin_id: "d-2".into(),
            ..coin
        });
        assert_eq!(snapshot.payment_due(0), 0);
        assert_eq!(snapshot.payment_due(1), 25);
    }

    #[test]
    fn generated_capability_has_valid_opaque_shape() {
        let capability = RoomCapability::generate().expect("random capability");
        assert!(capability.room_id.starts_with("room-"));
        assert!(valid_join_code(&capability.join_code));
    }

    #[test]
    fn invalid_join_codes_are_rejected_before_network_use() {
        assert!(!valid_join_code("PCH-ALICE"));
        assert!(!valid_join_code("PCH-0000-0000-0000-000Z"));
        assert!(!valid_join_code("PCH0000000000000000"));
    }

    #[test]
    fn immutable_account_credentials_are_scoped_by_authority() {
        let local = ClientConfig {
            uri: DEFAULT_URI.into(),
            database: DEFAULT_DATABASE.into(),
            account_id: "account-alice".into(),
        };
        let hosted = ClientConfig {
            uri: "https://maincloud.spacetimedb.com".into(),
            database: "poche-6quz6".into(),
            account_id: "account-alice".into(),
        };
        let staging = ClientConfig {
            database: "poche-staging".into(),
            ..hosted.clone()
        };
        let punctuation_variant = ClientConfig {
            account_id: "accountalice".into(),
            ..local.clone()
        };
        assert_eq!(
            credential_key(&local).len(),
            "poche-spacetimedb-".len() + 32
        );
        assert_ne!(credential_key(&local), credential_key(&punctuation_variant));
        assert_ne!(credential_key(&hosted), credential_key(&local));
        assert_ne!(credential_key(&hosted), credential_key(&staging));
    }

    fn quarter(room_id: &str, owner: Identity, coin_id: &str) -> Coin {
        Coin {
            coin_key: format!("{room_id}:{}:{coin_id}", owner.to_hex()),
            room_id: room_id.into(),
            owner,
            coin_id: coin_id.into(),
            denomination_cents: 25,
            container: "lid".into(),
            x_mm: 15,
            y_mm: 40,
            z_mm: 450,
            sequence: 3,
            committed_at: spacetimedb_sdk::Timestamp::UNIX_EPOCH,
        }
    }

    #[test]
    fn coin_cache_projection_is_room_scoped_and_does_not_authorize_private_card_faces() {
        let self_id = Identity::ONE;
        let peer_id = Identity::from_byte_array([2; 32]);
        let identity = self_id.to_hex().to_string();
        let rooms = [RoomView {
            room_id: "current".into(),
        }];
        let members = [
            MemberView {
                identity: identity.clone(),
                display_name: "Owner".into(),
                seat: Some(1),
                connected: true,
                is_self: true,
            },
            MemberView {
                identity: peer_id.to_hex().to_string(),
                display_name: "Peer".into(),
                seat: None,
                connected: true,
                is_self: false,
            },
        ];
        let rows = vec![
            quarter("current", peer_id, "q-000"),
            quarter("previous", self_id, "q-000"),
            quarter("current", self_id, "q-000"),
        ];
        let coins = coin_views(rows.clone(), &rooms, &members, Some(&identity));
        assert_eq!(coins.len(), 2);
        let own = coins.iter().find(|coin| coin.is_own).unwrap();
        assert_eq!(own.owner_seat, Some(1));
        assert_eq!(own.position_mm, [15, 40, 450]);
        assert_eq!(own.sequence, 3);
        assert_eq!(
            coins.iter().find(|coin| !coin.is_own).unwrap().owner_seat,
            None
        );
        let snapshot = ClientSnapshot {
            identity: Some(identity.clone()),
            coins,
            ..Default::default()
        };
        assert!(
            snapshot
                .coins
                .iter()
                .all(|coin| snapshot.visible_card_face(&coin.coin_key).is_none())
        );
        assert!(
            coin_views(rows, &[], &members, Some(&identity)).is_empty(),
            "leaving a room must clear coins even before coin-cache delete callbacks finish"
        );
    }

    #[test]
    fn coin_pose_update_preserves_logical_container_until_authority_commits_transfer() {
        let rooms = [RoomView {
            room_id: "room".into(),
        }];
        let mut row = quarter("room", Identity::ONE, "q-000");
        row.x_mm = 0;
        row.y_mm = 75;
        row.z_mm = 0;
        row.sequence = 4;
        let preview = coin_views([row.clone()], &rooms, &[], None);
        assert_eq!(preview[0].container, "lid");
        row.container = "bowl".into();
        row.sequence += 1;
        let committed = coin_views([row], &rooms, &[], None);
        assert_eq!(committed[0].container, "bowl");
        assert_eq!(committed[0].sequence, 5);
    }

    #[test]
    fn rejected_coin_transfer_remains_a_rejected_command_completion() {
        let (tx, rx) = mpsc::channel();
        finish_command::<String>(
            &tx,
            42,
            "move_coin",
            Instant::now(),
            Ok(Err("not your coin".into())),
        );
        let ClientEvent::CommandFinished {
            request_id,
            operation,
            result,
            ..
        } = rx.recv().unwrap()
        else {
            panic!("command completion expected")
        };
        assert_eq!(request_id, 42);
        assert_eq!(operation, "move_coin");
        assert_eq!(result, Err("not your coin".into()));
    }
}
